### ISSUE TITLE
I am having a problem in getting some attribute data in URLMetrics 

### ISSUE THREAD

**Issue by zohaibsheikh** [PavelMatua/Questions#1]
the PageAthority and DomainAthority attribute is coming to be zero , and my MozRank is also not printing. please have a look in this where i am doing something wrong and guide me please. 

![capture](https://user-images.githubusercontent.com/39086451/39753254-8e05c344-52d7-11e8-8fee-347ae55232f7.PNG)

**Comment by PavelMatua** [comment]
Thanks for your note. Actually it was an issue before, and I thought I had already fixed this bug. 

I've just committed new version to GITHUB. Now everything works fine.  
I'm closing your issue. Reopen if you have some problem.

**Comment by zohaibsheikh** [comment]
hi sir, i am having another issue now , i dont know what is it but i think it wasnt there before. when i ran the code for the very first time i think i restored some packages i dont know if its related to this issue or not , please have a look . i couldnt get to the part where i can see the other issue is resolved or not.i.e the PageAthority and DomainAthority attribute problem . 

![image](https://user-images.githubusercontent.com/39086451/39761795-7560ab90-52f2-11e8-9340-ea7e4060f7a3.png)

**Comment by PavelMatua** [comment]
Are you using LINQTOMOZ or LINQTOMOZ_Standard?
Are you executing the same query ?
I've tested LINQTOMOZ before committed.
Be sure that you run LINQTOMOZ not Standard and that you build well project.

**Comment by zohaibsheikh** [comment]
i am using LINKTOMOZ , and what do u mean by the same query ? i am just running this simple program .
![image](https://user-images.githubusercontent.com/39086451/39765359-1f6226ca-52fb-11e8-903f-843c4a7ad957.png)
and having this issue 
![image](https://user-images.githubusercontent.com/39086451/39765476-5bc53d64-52fb-11e8-8548-d6d29fe94aeb.png)

**Comment by zohaibsheikh** [comment]
can i ask what version of visual studio are you using currently ? mine is professional 2017 . i'd get another key from them and try it again .

**Comment by zohaibsheikh** [comment]
its working now .. but result is not same as the moz is providing . 
my pageauthority and domainauthority is a bit different then of moz's website. why is that ? :(
![image](https://user-images.githubusercontent.com/39086451/39767254-bbf89e48-52ff-11e8-8fbf-12855c7c033a.png)

**Comment by zohaibsheikh** [comment]
is it possible to run url directly ? because i couldnt made that signature and everytime i made it they wont sent the data, so i thought they dont allow the direct hit on their data so i used your library... i tried all the converter to make that signature and then tried to call but data wont come ..
